# Generated by Django 4.1.3 on 2022-11-30 12:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(auto_now_add=True)),
                ('beautyTitle', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('other_titles', models.CharField(blank=True, max_length=256)),
                ('connect', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[(1, 'new'), (2, 'pending'), (3, 'accepted'), (4, 'rejected')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.images')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.pereval')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.area')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.pereval')),
            ],
        ),
        migrations.AddField(
            model_name='pereval',
            name='area',
            field=models.ManyToManyField(through='perevalapp.PerevalArea', to='perevalapp.area'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='coord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.coords'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='image',
            field=models.ManyToManyField(through='perevalapp.PerevalImages', to='perevalapp.images'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.level'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perevalapp.users'),
        ),
    ]
