# Generated by Django 4.1.3 on 2022-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], max_length=2),
        ),
    ]
