# Generated by Django 4.1.3 on 2022-11-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pereval',
            name='level',
        ),
        migrations.AddField(
            model_name='pereval',
            name='level_autumn',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level_spring',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level_summer',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level_winter',
            field=models.CharField(blank=True, choices=[(1, '1А'), (2, '1Б'), (3, '2А'), (4, '2Б'), (5, '3А'), (6, '3Б')], default='', max_length=2),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
