# Generated by Django 4.1.3 on 2022-11-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0003_remove_pereval_level_pereval_level_autumn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
