# Generated by Django 4.1.3 on 2022-12-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0005_image_alter_pereval_image_alter_perevalimages_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerevalImages',
            new_name='PerevalImage',
        ),
    ]
