# Generated by Django 4.1.3 on 2022-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0006_rename_perevalimages_perevalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='image',
            field=models.ManyToManyField(related_name='images', through='perevalapp.PerevalImage', to='perevalapp.image'),
        ),
    ]
